# Generated by Django 4.2.2 on 2023-07-18 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentApp', '0002_ciudad_comuna_arrendatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=150)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='ultimo_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_cientifico', models.CharField(max_length=150)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamaño_m2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.CharField(choices=[('Arbol', 'Arbol'), ('Arbusto', 'Arbusto'), ('Flores', 'Flores'), ('Suculenta', 'Suculenta'), ('Cactus', 'Cactus')], max_length=20)),
                ('perenne', models.BooleanField(default=False)),
                ('riego', models.CharField(max_length=200)),
                ('cuidados', models.TextField()),
                ('stock', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp.caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=15)),
                ('rol', models.CharField(max_length=100)),
                ('FechaRegistro', models.DateTimeField(auto_now=True)),
                ('ultimo_login', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
