# Generated by Django 4.2.2 on 2023-07-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0004_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp.pedido')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp.ejecutivo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp.pedido')),
            ],
        ),
    ]
