# Generated by Django 4.2.3 on 2023-07-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0005_planta_pedido_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendatario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='arrendatario',
            name='nombres',
        ),
    ]
