# Generated by Django 4.2.3 on 2023-07-20 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentApp', '0007_alter_arrendatario_rut_alter_arrendatario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendatario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
