# Generated by Django 4.2.3 on 2023-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0009_planta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='caracteristica',
        ),
        migrations.AddField(
            model_name='planta',
            name='caracteristica',
            field=models.ManyToManyField(to='rentApp.caracteristica'),
        ),
    ]
