# Generated by Django 4.2.3 on 2023-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0010_remove_planta_caracteristica_planta_caracteristica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='altura',
            field=models.CharField(max_length=90),
        ),
    ]
