# Generated by Django 4.2.3 on 2023-07-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0011_alter_planta_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
