# Generated by Django 4.2.3 on 2023-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0012_planta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='riego',
            field=models.CharField(max_length=500),
        ),
    ]
