# Generated by Django 4.2.3 on 2023-07-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0013_alter_planta_riego'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='familia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='floracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
