# Generated by Django 4.2.3 on 2023-07-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0015_admin_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecutivo',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
