# Generated by Django 4.2.3 on 2023-08-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0017_pedido_ejecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentApp.comuna'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ejecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentApp.ejecutivo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
