# Generated by Django 4.2.3 on 2023-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0018_alter_pedido_comuna_alter_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='proceso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
