# Generated by Django 4.2.3 on 2023-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0019_pedido_proceso_pedido_terminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='seleccionPlantasLista',
            field=models.BooleanField(default=False),
        ),
    ]
