# Generated by Django 4.2.2 on 2023-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0020_pedido_seleccionplantaslista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
