# Generated by Django 4.2.2 on 2023-08-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0021_alter_pedido_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
