# Generated by Django 4.2.3 on 2023-08-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0022_alter_planta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='archivada',
            field=models.BooleanField(default=False),
        ),
    ]
