# Generated by Django 4.2.2 on 2023-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0023_planta_archivada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='caracteristica',
            field=models.ManyToManyField(blank=True, to='rentApp.caracteristica'),
        ),
    ]
