# Generated by Django 4.2.3 on 2023-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0024_alter_planta_caracteristica'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeAnonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('asunto', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(max_length=300)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
