# Generated by Django 4.2.3 on 2023-08-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0025_mensajeanonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeanonimo',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mensajeanonimo',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
