# Generated by Django 4.2.3 on 2023-08-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0026_mensajeanonimo_fecha_mensajeanonimo_leido'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaMensajeAnonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp.admin')),
                ('mensajeAnonimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentApp.mensajeanonimo')),
            ],
        ),
    ]
