# Generated by Django 4.2.2 on 2023-09-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentApp', '0027_respuestamensajeanonimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendatario',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='arrendatario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='arrendatario',
            name='numero_direccion',
        ),
    ]
